version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "53215:53215"
    environment:
      - PORT=53215
      - NODE_ENV=production
    networks:
      - maritime-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:53215
      - PORT=3000
    depends_on:
      - backend
    networks:
      - maritime-network
    restart: unless-stopped

networks:
  maritime-network:
    driver: bridge

volumes:
  # Add any persistent volumes here if needed in the future
  # For example, if you add a database or need to persist logs