version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "53215:53215"
    environment:
      - PORT=53215
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "56940:56940"
    environment:
      - PORT=56940
      - REACT_APP_API_URL=http://localhost:53215
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend